<a href="https://colab.research.google.com/github/riassnti/riassnti/blob/master/Pertemuan_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **STRUKTUR DATA PYTHON**

A. STRUKTUR DATA

1. Lists

In [10]:
aLists = ["John", 33, "Toronto", True]
aLists

['John', 33, 'Toronto', True]

In [11]:
type(aLists)

list

In [14]:
bin_colors=['Red', 'Green', 'Blue', 'Yellow']

2. Tuples

In [15]:
bin_colors=['Red', 'Green', 'Blue', 'Yellow']
print(f"The second element of the tuple is {bin_colors[1]}")

The second element of the tuple is Green


In [17]:
print(f"The elements after thrid element onwards are {bin_colors[2:]}")

The elements after thrid element onwards are ['Blue', 'Yellow']


In [21]:
nested_tuple = (1,2,(100,200,300),6)
print(f"The maximum value of the inner tuple {max(nested_tuple[2])}")

The maximum value of the inner tuple 300


3. Dictionary

In [25]:
bin_colors = {
  "manual_color" : "Yellow",
  "approved_color" : "Green",
  "refused_color" : "Red"
}

In [26]:
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}


In [27]:
bin_colors.get('approved_color')

'Green'

In [31]:
bin_colors['approved_color']

'Green'

In [46]:
bin_colors['approved_color']= "Purple"

In [47]:
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Purple', 'refused_color': 'Red'}


4. Sets

In [48]:
green = {'grass', 'leaves'}
print(green)

{'leaves', 'grass'}


In [50]:
yellow = {'dandelions', 'fire hydrant', 'leaves'}
red = {'fire hydrant', 'blood', 'rose', 'leaves'}

In [51]:
print(f"The union of yellow and red sets is {yellow|red}")

The union of yellow and red sets is {'rose', 'blood', 'dandelions', 'fire hydrant', 'leaves'}


In [52]:
print(f"The intersaction of yellow and red is {yellow&red}")

The intersaction of yellow and red is {'fire hydrant', 'leaves'}


5. DataFrames

5.1. DataFrame

In [94]:
import pandas as pd
df = pd.DataFrame([
    ['1', 'Thasya', 30, True],
    ['2', 'Nurul', 20, False],
    ['3', 'Yostantina', 19, True]])
df.columns = ['no', 'nama', 'umur', 'keterangan']
print(df)

  no        nama  umur  keterangan
0  1      Thasya    30        True
1  2       Nurul    20       False
2  3  Yostantina    19        True


5.1.1. Column Selection

In [95]:
df[['nama', 'umur']]

nama  umur
0      Thasya    30
1       Nurul    20
2  Yostantina    19

In [96]:
df.iloc[:,3]

0     True
1    False
2     True
Name: keterangan, dtype: bool

5.1.2. Row Selection

In [97]:
df.iloc[1:3,:]

no        nama  umur  keterangan
1  2       Nurul    20       False
2  3  Yostantina    19        True

In [99]:
df[df.umur<20]

no        nama  umur  keterangan
2  3  Yostantina    19        True

6. Matrix

In [100]:
import numpy as np
myMatrix = np.array([[11,12,13], [21,22,23], [31,32,33]])

In [101]:
print(myMatrix)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [102]:
print(type(myMatrix))

<class 'numpy.ndarray'>


In [103]:
myMatrix.transpose()

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

B. TIPE DATA ABSTRAK

1. Vector

In [104]:
myVector = [1,2,3,4,5]
print(myVector)

[1, 2, 3, 4, 5]


In [105]:
print(type(myVector))

<class 'list'>


In [106]:
myVector = np.array([1,2,3,4,5])
print(myVector)

[1 2 3 4 5]


In [107]:
print(type(myVector))

<class 'numpy.ndarray'>


2. Stack

In [108]:
class Stack:
    def __init__(self):
        self.items = []
    def isEmpty(self):
        return self.items == []
    def push(self, item):
        self.items.append(item)
    def pop(self):
        return self.items.pop()
    def peek(self):
        return self.items[len(self.items)-1]
    def size(self):
        return len(self.items)
    

# **Populate The Stack**

In [80]:
stack=Stack()
stack.push('Pink')
stack.push('Purple')
stack.push('Black')
stack.push('Grey')


**Pop**

In [110]:
stack.pop()

'Purple'

In [111]:
stack.isEmpty()

False

In [112]:
colors = ['Pink']

In [113]:
colors.append('Purple')
colors.append('Black')
colors.append('Grey')


In [114]:
colors

['Pink', 'Purple', 'Black', 'Grey']

3. Queue

In [115]:
class Queue(object):
  def __init__(self):
      self.items = []
  def isEmpty(self):
      return self.items == []
  def enqueue(self, item):
      self.items.insert(0,item)
  def dequeue(self):
      return self.items.pop()
  def size(self):
      return len(self.items)

In [116]:
queue = Queue()

In [117]:
queue.enqueue('Pink')

In [118]:
queue.enqueue('Purple')

In [119]:
queue.enqueue('Black')

In [120]:
queue.enqueue('Grey')

In [121]:
print(f"Size of queue is {queue.size()}")

Size of queue is 4


In [122]:
print(queue.dequeue())

Pink
